services:
  db:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017"

  redis:
    image: redis:alpine
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379"

  apiartist:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --log-level info"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis


volumes:
  mongo_data:
