name: Production Test API Artist

on:
  push:
    branches:
      - Production

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 